### ISSUE TITLE
Improving workflow

### ISSUE THREAD

**Issue by phuongnd** [cleversoft/zt-portfolio#1]
Giao diện admin sẽ giống như hình bên dưới: 

![ztportfolio1](https://cloud.githubusercontent.com/assets/5260516/10212718/61c7d08e-682d-11e5-87e8-a50a1fe85f01.png)
1. Properties: 
- Rename Header Editor => Properties 
- Cho phép tạo properties: date, input, link, media ( image, video, soundcloud )
1. Categories 
- Cho phép tạo category. 
- Các properties tạo ở bước 1, sẽ tự động gán chung cho các category 
1. Items 

![ztportfolio2](https://cloud.githubusercontent.com/assets/5260516/10212721/6ae71972-682d-11e5-8a47-25090263eb0d.png)
- Cho phép chọn multi category 
- Cho phép chọn image 
- Cho phép điền Short description 
- Cho phép điền Description 
- Cho phép điền các properties (  Leave this filed blank if property is not required. )

**Comment by phuongnd** [comment]
1. khi tạo property 
- Remove phần category name 
- Type có 4 kiểu sau: date, input, link, media ( image, video, soundcloud )
- Mỗi property sẽ không có ràng buộc gì với category 
1. Khi tạo mới 1 portfolio, em sửa lại layout theo hình sau https://cloud.githubusercontent.com/assets/5260516/10212721/6ae71972-682d-11e5-8a47-25090263eb0d.png

thứ tự từ trái qua phải: 

CỘT TRÁI: 
1. title 
2. alias 
3. image 
4.  ( option property được tạo ở step 1 ) 
- video URL 
- URL 
- Created Date 
1. Short Des 
2. Des

CỘT PHẢI: 
1. category 
2. Status 
3. Language 
4. Access

**Comment by phuongnd** [comment]
1.Properties: 
- Bổ xung button Add New Property. Xem image bên dưới 
  ![zt-portfolio-property](https://cloud.githubusercontent.com/assets/5260516/10558323/b6abe0a2-74f5-11e5-8151-7a43f7a71dec.png)
1. Items ( Portfolios ) 
- Khi tạo mới item portfolio thì phần Properties chưa hiển thị đúng. Ví dụ admin tạo ra các properties: 
- Date (kiểu date) 
- Client (kiểu text) 
- Live Demo ( kiểu text)

=> Nhưng hiện tại admin vẫn chưa thể điền được giá trị của 3 properties trên 

Form đúng sẽ giống https://cloud.githubusercontent.com/assets/5260516/10212721/6ae71972-682d-11e5-8a47-25090263eb0d.png

**Comment by chiro-hiro** [comment]
Anh xem lại ! cái properties nó đâu có phải như anh nói

**Comment by chiro-hiro** [comment]
Nó chỉ cho người dùng chọn properties và add vào thôi

**Comment by phuongnd** [comment]
Nó là như vậy đó e! Có vẻ e không dành time cho project này! Nên mọi cái a thấy rất hời hợt! Nếu e không có time cho project, thì thẳng thắn báo lại! Để a còn sắp xếp cv!

**Comment by phuongnd** [comment]
![portfolio-properties](https://cloud.githubusercontent.com/assets/5260516/10568073/5baeddd2-763d-11e5-844c-a7cd06e7d512.png)
