### ISSUE TITLE
Pkg portfolio could not be install !!!

### ISSUE THREAD

**Issue by thanhppm** [cleversoft/zt-portfolio#12]
Warning
JInstaller: :Install: SQL File not found C:\xampp\htdocs\windy100\administrator\components\com_ztportfolio/admin/sql/install/mysql/install.sql
Extension Install: SQL error processing query: DB function reports no errors.
Package Install: There was an error installing an extension: com_ztportfolio.zip
Error

Error installing package

**Comment by Thuan1234** [comment]
fixed
